### ISSUE TITLE
A question about web-search index

### ISSUE THREAD

**Issue by jinweilin7325** [parsa-epfl/cloudsuite#147]
I am using web_search with docker.  Each time I restart the container, it would download the index again, this takes much time. Is there any way to save some time from this situation ? I am currently using docker pause/unpause to prevent restarting the server, but I am afraid if the machine crashes when server is running , I would start again from the beginning.

**Comment by rahulketch** [comment]
You can download the index once on your machine and then change the server to use that index instead of downloading it every time. 
Add the following to cloudsuite/benchmarks/web-search/server/Dockerfile after downloading the index in the same directory.

`COPY index /index  `

In cloudsuite/benchmarks/web-search/server/docker-entrypoint.sh, change:
```
#Download the index
wget -O - $INDEX_URL \
  | tar zxvf - -C $SOLR_CORE_DIR/cloudsuite_web_search*
```
to
```
#Download the index                                                             
tar zxvf /index -C $SOLR_CORE_DIR/cloudsuite_web_search*
```
Build and run this new server image and it should be faster. 
Hope that helps.

**Comment by rahulketch** [comment]
Closing the issue. Feel free to reopen if any more questions.

**Comment by jinweilin7325** [comment]
Thanks for your help!  your solution worked for me. But sometimes when I try to build a server image, it reportes 
`Step 24/29 : COPY index /index`
`Error processing tar file(exit status 1): unexpected EOF` 
I have checked the  permissions of Dockerfile and index， they are both owned by root.
Do you have any idea what may be the causes of this error ?
