### ISSUE TITLE
in-memory analytics WARN Executor: 1 block locks were not released by TID

### ISSUE THREAD

**Issue by rkgithubs** [parsa-epfl/cloudsuite#201]
while running more than 1 docker instance of in-memory analytics on Cent OS, I'm seeing the following warning quite often. Also, CPU Utilization% fluctuates which suggests that this more than benign warning- there are potential locking problems in this test stopping it from scaling. 

19/01/02 16:59:25 WARN Executor: 1 block locks were not released by TID = 1841:
[rdd_237_0]
19/01/02 16:59:25 WARN Executor: 1 block locks were not released by TID = 1842:

Is there a solution to this issue, we'd ideally like to run multiple instances of these tests.

**Comment by ZiluTian** [comment]
Hi, 
Have you checked the memory usage? I tested on CentOS with 24 core setup for three clients, one master, and I am able to run the benchmark successfully using the updated images (https://cloud.docker.com/repository/docker/zilutian/in-memory-analytics). Please provide more details if the problem is still relevant. Thank you!

Regards, 
Zilu
