### ISSUE TITLE
Questions about enable_materialized_views in docker image 

### ISSUE THREAD

**Issue by hh-project-config** [parsa-epfl/cloudsuite#224]
Thanks for providing this useful container (https://hub.docker.com/r/cloudsuite/cassandra).  

I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` 
It seems the official document (http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html) says "Materialized views are considered experimental and are not recommended for production use." And the default value for these two parameters are *False* in the document. They say they will disable them in Cassandra 4.

However, in the latest version of Cassandra (3.11.4), the default value for them are still *True* , as is the setting in your container's cassandra.yaml. 

Shall we disable them manually for now? 
Thanks!

**Comment by ZiluTian** [comment]
Hello, 
Materialized views are most useful if you have complex queries. In our release, Cassandra is used as the backend for Data Caching workload (serve memcached requests) and Data Serving workload (YCSB load generator, can define your mix of workload with different read/write ratio), none of them involves complex queries that might benefit from materialized view. However, there might be specific queries you would like to benchmark against which can benefit from such option (consider example shown here: https://www.datastax.com/dev/blog/materialized-view-performance-in-cassandra-3-x) Otherwise, please feel free to disable it.  

Regards, 
Zilu
