### ISSUE TITLE
Spark based benchmark cannot run by overlay

### ISSUE THREAD

**Issue by lpcclown** [parsa-epfl/cloudsuite#225]
I tried both `graph analytics` and `in-memory analytics` by using the overlay network. However, None of them is working. It pops below error:
![image](https://user-images.githubusercontent.com/7920916/62384917-9af7f380-b521-11e9-8058-4b7cd2ff4ab0.png)

The client cannot find the master node. I have opened all the TCP ports, so it should not be TCP port issue. Meanwhile, I tried cloudsuite pure spark setup on the overlay, it can successfully run the PI calculation. 

Could you please provide some suggestions? Thanks

**Comment by lpcclown** [comment]
In case, the error is not clear in the picture. The error is "Failed to connect to master spark-master:7077". If you need more detail, please let me know, I am happy to provide. Thanks

**Comment by ZiluTian** [comment]
Hello, 
Can you please post the exact commands you used to launch the master, worker, and client? 

Thanks, 
Zilu

**Comment by lpcclown** [comment]
Hi Zilu, thanks for your swift response.
These are the commands I used:
1. Create a docker swarm:
`docker swarm init`
2. Worker joins the created swarm:
`docker swarm join --token 'the token' 'IPAddress':2377`
3. Create an attachable overlay network on the swarm master node:
`docker network create --driver=overlay --attachable spark-net`
4. Launch the master docker container
`docker run -dP --net spark-net --hostname spark-master --name spark-master cloudsuite/spark master`
5. Launch the worker docker container
`docker run -dP --net spark-net --volumes-from data --name spark-worker  cloudsuite/spark worker spark://spark-master:7077` 
6. Run the benchmark on the overlay network
` docker run --rm --net spark-net --volumes-from data  cloudsuite/graph-analytics  --driver-memory 2g --executor-memory 8g  --master spark://spark-master:7077`

From step 1 to step 5, there is no error. And before step 1, I have already downloaded the required docker images. On step 6, it pops the error. I ran them on AWS two EC2 instances. I opened the TCP port as any inbound for these two AWS EC2 servers. And I tried to run step 6 on both master and worker nodes, they poped the same error. 

Is there any more information you required, kindly let me know, really appreciated.

**Comment by ZiluTian** [comment]
Hello, 
Sorry for the delay. There was a technical issue with our cluster. Please use our updated image available as zilutian/graph-analytics:amd64. I was able to reproduce your issue with the outdated image and confirmed that it had been fixed with the update. Please let me know if you have any further questions. 

Regards, 
Zilu

**Comment by ZiluTian** [comment]
Please also note that there is a default executor memory set to 2g for in-memory analytics in src file to prevent executor not having enough memory. If you would like to test with different executor setting, please remove that line and generate a new image, otherwise your setting will be overwritten. This change will be considered for integration in the future. Sorry for any inconvenience. https://github.com/parsa-epfl/cloudsuite/blob/zilu_django/benchmarks/in-memory-analytics/3.0/movielens-als/src/main/scala/MovieLensALS.scala.
