### ISSUE TITLE
How to Run benchmark and produce result

### ISSUE THREAD

**Issue by aadewojo** [parsa-epfl/cloudsuite#235]
I have pulled and started the docker containers, however, I do not know how to run this benchmark nor how to make it simulate events and get results.

Could someone please show me the way.

Thanks.

**Comment by ZiluTian** [comment]
Hi, 

The first step for getting started is the documentation page cloudsuite.ch. Another great source is https://hub.docker.com/u/zilutian, which contains step-by-step instruction and expected output. If you have any specific question regarding a particular workload, please open another issue and we will try to help. 

Regards, 
Zilu

**Comment by aadewojo** [comment]
Thank you. I couldn't get any detail on the main site. But I will have a
look at the other link. Does it mean I have to pull another set of docker
images for the other link or can I keep using the original one while I
follow the link?

**Comment by ZiluTian** [comment]
Hi, 

Depending on the workload, you may need to pull new images (e.g. data caching is the same in both cases). The main difference between the updated images and original ones is the version of the software stack and some minor modifications in the benchmark code which adapts to the update. Previous version can be buggy. 

If you have limited network access, slow network, or the traffic is a concern, and you are simply trying out the workloads without using them as benchmark tools for profiling your system, you can try to replace the image names in the instruction with your existing local image names and it will work for a few workloads. Otherwise, I strongly suggest that you pull the alternative images from which the expected output is obtained.

Regards, 
Zilu

**Comment by neo-apz** [comment]
On the main website if you click on any of the benchmark links you will get redirected to the documentation page of that benchmark. You can find all the docs in this folder:
https://github.com/parsa-epfl/cloudsuite/tree/master/docs/benchmarks

**Comment by aadewojo** [comment]
Ok. Thank you very much. I will let you know how it goes.

**Comment by aadewojo** [comment]
Thanks for the info. That was exactly the documentation I used to get to
the point I am, but it isn't detailed enough to let me know how to run
experiments and get results.
